apps/sharefile/urls.py
# _*_ coding: utf-8 _*_
from sharefile.views.FileDetailView import FileDetailView

_author_ = 'Ace'
_date_ = '2019-01-30 15:57'


from sharefile.views.AddfileView import AddfileView
from sharefile.views.FileListView import FileListView
from sharefile.views.ProjectListView import ProjectListView
from sharefile.views.ProccessView import ProcessView
from sharefile.views.ReviewFileView import ReviewFileView

from django.urls import path, include, re_path
# from . import views
from sharefile import views
from sharefile.views.FileDel import del_file
# from . import views

app_name = 'sharefile'


urlpatterns = [
        path('addfile/', AddfileView.as_view(), name='addfile'),
        path('filelist/', FileListView.as_view(), name='filelist'),
        path('filedetail/', FileDetailView.as_view(), name='filedetail'),
        path('process/', ProcessView.as_view(), name='process'),
        path('project_list/',ProjectListView.as_view(), name='project'),
        path('review/', ReviewFileView.as_view(), name="review"),
        path('delete_file/',views.FileDel.del_file, name='delete_file'),
        # path(r'^del_student/',views.FileDel.del_file),

        # re_path('filelist/(?P<pk>\d+)/',FileListView.as_view(), name='filelist'),
        # re_path('filedownload/(?P<product_id>\d+)/', CountDownloadView.as_view, name='countdownload'),
        # path('buttons/', ButtonsView.as_view(), name='buttons'),
        # path('edit/', EditView.as_view(), name='edit'),
        # path('wheel/', WheelView.as_view(), name='wheel'),
        #删除
        # path(r'^del-file/$', views.del_file, name="del_file"),
        # path('delete_file/',views.del_file, name='delete_file'),
        ]

apps/users/urls.py
from django.urls import path

from users.views.UpdatePwdView import UpdatePwdView
# from users.views.UploadImageView import UploadImageView
from users.views.home import homeview
from users.views.Addproject import Addproject
from users import views
from users.views.UploadImageView import Upload_image


app_name = 'users'
# urlpatterns = [
#     path('register',RegisterView.as_view,name='profile')
# ]


urlpatterns = [
        path('home/', homeview.as_view(), name='home'),
        path('addproject/', Addproject.as_view(), name='addproject'),
        path('imageupload/', views.UploadImageView.Upload_image ),# 用户头像上传
        # 用户个人中心修改密码
        path('update/pwd/', UpdatePwdView.as_view(), name="update_pwd"),
        ]

share2/urls.py
import logging

from django.contrib import admin
from django.urls import path, include, re_path

from users.views.Index import Index
from users.views.LoginView import LoginView
from users.views.RegisterView import RegisterView
from users.views.LogoutView import LogoutView
from users.views.ActiveUserView import ActiveUserView
from users.views.ForgetPwdView import ForgetPwdView
from users.views.ResetView import ResetView
from users.views.ModifyPwdView import ModifyPwdView

from users.views.test import testview

import xadmin

# 用于设定图片URL地址
from django.views.static import serve
# 配件添加图片URL时用到的
from .settings import MEDIA_ROOT

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),

    # 主页
    re_path(r'^$', Index.as_view(), name="index"),

    path('index/', Index.as_view(), name="index"),
    path('test/', testview.as_view(), name="test"),

    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name="register"),

    # 忘记密码
    path('forget/', ForgetPwdView.as_view(), name="forget_pwd"),
    # 重置密码urlc ：用来接收来自邮箱的重置链接, 用于在邮箱里面点击后，所要跳转到的页面链接
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
    # 修改密码url; 用于passwordreset页面提交表单, 用于点击来链接里面提交密码。
    path('modify_pwd/', ModifyPwdView.as_view(), name="modify_pwd"),

    # 验证码url
    path("captcha/", include('captcha.urls')),
    # 激活用户url
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name="user_active"),

    # sharefile的URL
    path("sharefile/", include('sharefile.urls', namespace='sharefile')),
    # users的URL
    path("users/", include('users.urls', namespace='users')),
    # 处理图片显示的url,使用Django自带serve,传入参数告诉它去哪个路径找，我们有配置好的路径MEDIAROOT， 其中document_root是一个固定写法。
    re_path('media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

apps/users/forms/LoginForm.py
# _*_ coding: utf-8 _*_
_author_ = 'Ace'
_date_ = '2019-01-29 14:26'

from django.core.exceptions import ValidationError
from django import forms as django_forms
from django.forms import fields as django_fields
from  django import forms
from .base import BaseForm

# Way1
class LoginForm(forms.Form):
    # 用户名密码不能为空
    username = forms.CharField(required=True)
    # 密码不能小于5位
    password = forms.CharField(required=True, min_length=5)
    #记住密码
    rmb = django_forms.IntegerField(required=False)

apps/users/forms/RegisterForm.py
# _*_ coding: utf-8 _*_
_author_ = 'Ace'
_date_ = '2019-01-29 14:28'


from django import forms as django_forms
from django.forms import fields as django_fields


from .base import BaseForm

# class RegisterForm(BaseForm, django_forms.Form):
#     username = django_fields.CharField()
#     password = django_fields.CharField()
#     confirm_pwd = django_fields.CharField()
#
#     def clean(self):
#         v1 = self.cleaned_data['password']
#         v2 = self.cleaned_data['confirm_pwd']
#         if v1 == v2:
#             pass
#         else:
#             from django.core.exceptions import ValidationError,NON_FIELD_ERRORS
#             raise ValidationError('密码输入不一致')

from captcha.fields import CaptchaField
from  django import forms

# 验证码form & 注册表单form
class RegisterForm(forms.Form):
    # 此处email与前端name需保持一致。
    # 账号
    username = forms.CharField(required=True)
    # 邮箱
    email = forms.EmailField(required=True)
    # 密码不能小于5位
    password = forms.CharField(required=True,min_length=5)
    # 应用验证码 自定义错误输出key必须与异常一样
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})

apps/users/forms/base.py
# _*_ coding: utf-8 _*_
_author_ = 'Ace'
_date_ = '2019-01-29 14:28'
'''
这里是复杂别人博客项目的，我做参考使用的。

'''
class BaseForm(object):
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(BaseForm, self).__init__(*args, **kwargs)

apps/users/views/LoginView.py
# _*_ coding: utf-8 _*_




from django.contrib.auth import login, authenticate
from django.db.models import Q

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render,redirect

# 基于类实现需要继承的view
from django.urls import reverse
from django.views.generic.base import View

from repository.models import UserProfile
from users.forms.LoginForm import LoginForm



#https://blog.csdn.net/zhangmengran/article/details/83547634
'''
尝试使用Absouble User试
'''

# Wa1 要匹配form
class LoginView(View):
    # 直接调用get方法免去判断
    def get(self, request):
        # render就是渲染html返回用户
        # render三变量: request 模板名称 一个字典写明传给前端的值
        redirect_url = request.GET.get('next', '')
        return render(request, "login.html", {
            "redirect_url": redirect_url
        })

    def post(self, request):
        result = {'status': False, 'message': None, 'data': None}
        # 类实例化需要一个字典参数dict:request.POST就是一个QueryDict所以直接传入
        # POST中的usernamepassword，会对应到form中
        login_form = LoginForm(request.POST)
        # 默认false
        request.session["is_login"] = False
        # is_valid判断我们字段是否有错执行我们原有逻辑，验证失败跳回login页面
        if login_form.is_valid():
            # 取不到时为空，username，password为前端页面name值
            user_name = request.POST.get("username", "")
            pass_word = request.POST.get("password", "")
            print("user_name", user_name, "pass_word", pass_word)

            # 成功返回user对象,失败返回null
            user = authenticate(username=user_name,password=pass_word)

            if user is not None:
                # 只有当用户激活时才给登录
                if user.is_active:
                    # login_in 两参数：request, user
                    # 实际是对request写了一部分东西进去，然后在render的时候：
                    # request是要render回去的。这些信息也就随着返回浏览器。完成登录
                    login(request, user)
                    # 跳转到首页 user request会被带回到首页
                    # 增加重定向回原网页。


                    # 存入session 序列化用户对象
                    user_dict = {}
                    user_ser = UserProfile.objects.filter(username=user_name)[0]
                    user_dict["is_admin"] = user_ser.is_admin
                    # user_dict["is_admin"] = user_ser.is_admin
                    # user_dict["is_approver"] = user_ser.is_approver
                    user_dict["is_approver"] = user_ser.is_approver
                    user_dict["user_name"] = user_ser.username
                    user_dict['user_id'] = user_ser.id
                    
                    request.session["user"] = user_dict
                    request.session["is_login"] = True
                    print("登录-----", user_dict)
                    # 增加重定向回原网页。

                    redirect_url = request.POST.get('next', '')
                    if redirect_url:
                        return HttpResponseRedirect(redirect_url)
                    # 跳转到首页 user request会被带回到首页
                    return HttpResponseRedirect(reverse("index"))
                # 即用户未激活跳转登录，提示未激活
                else:
                    return render(
                        request, "login.html", {
                            "msg": "用户名未激活! 请前往邮箱进行激活"})
            # 仅当用户真的密码出错时
            else:
                return render(request, "login.html", {"msg": "用户名或密码错误!"})
        # 验证不成功跳回登录页面
        # 没有成功说明里面的值是None，并再次跳转回主页面
        else:
            return render(
                request, "login.html", {
                    "login_form": login_form})

apps/users/views/RegisterView.py
# _*_ coding: utf-8 _*_
from django.contrib.auth.hashers import make_password
from django.shortcuts import render
from django.contrib.auth.models import User
from users.forms.RegisterForm import RegisterForm

# 基于类实现需要继承的view
from django.views.generic.base import View

from repository.models import UserProfile
from utils.email_send import send_register_eamil

from django.contrib import auth
from django.contrib.auth.models import User


class RegisterView(View):
    # get方法直接返回页面
    def get(self, request):
        # 添加验证码
        register_form = RegisterForm()
        return render(
            request, "register.html", {
                'register_form': register_form})

    def post(self, request):
        # 实例化form
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            # 这里注册时前端的name为email
            user_email = request.POST.get("email", "")
            user_name = request.POST.get("username", "")
            user_password = request.POST.get("password", "")
            # print("-"*50)
            # print("user_name", user_name)
            # print("-" * 50)
            # 用户名查重
            if UserProfile.objects.filter(username=user_name):
                return render(
                    request, "register.html", {
                        "register_form": register_form, "msg": "用户已存在"})
            if UserProfile.objects.filter(email=user_email):
                return render(
                    request, "register.html", {
                        "register_form": register_form, "msg": "邮箱已经被占用了"})

            # 实例化一个user_profile对象，将前台值存入
            user_profile = UserProfile()


            user_profile.username = user_name
            user_profile.email = user_email

            # # 默认激活状态为false
            # user_profile.is_active = False

            # 加密password进行保存
            user_profile.password = make_password(user_password)
            user_profile.save()

            # 写入欢迎注册消息
            # user_message = UserMessage()
            # user_message.user = user_profile.id
            # user_message.message = "欢迎注册!! --系统自动消息"
            # user_message.save()
            # 发送注册激活邮件
            # send_register_eamil(user_email, "register")

            # 跳转到登录页面
            return render(request, "login.html", )
        # 注册邮箱form验证失败
        else:
            return render(
                request, "register.html", {
                    "register_form": register_form})

templates/Ace-add-project.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title text-uppercase">DEPARTMENT DETAILS</h5>
                                <form class="form-material m-t-40" action="{% url 'users:addproject' %}" method="post" enctype="multipart/form-data">
                                    <div class="form-group">
                                        <div class="row">
                                            <label class="col-md-12" for="example-text">Name</span>
                                            </label>
                                            <div class="col-md-12">
                                                <input type="text" id="example-text" name="project" class="form-control" placeholder="enter name">
                                            </div>
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Submit</button>
                                    <button type="submit" class="btn btn-dark waves-effect waves-light">Cancel</button>
                                {% csrf_token %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock %}

templates/Ace-dashboard-table-basic.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
                <!-- column -->
{#                <div class="col-12">#}
{#                    <div class="card">#}
{#                        <div class="card-body">#}
{#                            <h4 class="card-title">最新下载统计</h4>#}
                            {#                                <h6 class="card-subtitle">Add<code>.table-bordered</code>for borders on all sides of the table and cells.</h6>#}
{#                            <div class="table-responsive">#}
{#                                <table class="table table-bordered">#}
{#                                    <thead>#}
{#                                    <tr>#}
{#                                        <th>文件名称</th>#}
{#                                        <th>下载数量</th>#}
{#                                        <th>上传时间</th>#}
{#                                        <th class="text-nowrap">描述</th>#}
{#                                    </tr>#}
{#                                    </thead>#}
{#                                    <tbody>#}
{#                                    {% for file in allfile %}#}
{#                                        <tr>#}
{#                                            <td>{{ file.models_Filename }}</td>#}
{#                                            <td>#}
{#                                                <div class="progress progress-xs margin-vertical-10 ">#}
{#                                                    <div class="progress-bar bg-danger"#}
{#                                                         style="width: 35%; height:6px;"></div>#}
{#                                                </div>#}
{#                                            </td>#}
{#                                            <td>{{ file.models_Updated_date }}</td>#}
{#                                            <td class="text-nowrap">#}
{#                                                {{ file.models_Filedes }}#}
{#                                            </td>#}
{#                                        </tr>#}
{#                                    {% endfor %}#}
{#                                    </tbody>#}
{#                                </table>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
                <!-- column -->
                <!-- column -->
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">最新上载统计</h4>

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>文件名称</th>
                                        <th>上传者</th>
                                        <th>上传日期</th>
                                        <th>用于</th>
                                        <th>部门</th>
                                        <th>描述</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for file in allfile %}
                                        <tr>
                                            <td><a href="{{ MEDIA_URL }}{{ file.models_Fileupload }}" download="">{{ file.models_Filename }}</a></td>
                                            <td>Ace</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i>{{ file.create_time }}</span></td>
                                            <td>{{ file.models_Fileproject }}</td>
                                            <td>
                                                <div class="label label-table label-success">{{ file.department }}</div>
                                            </td>
                                            <td>{{ file.models_Filedes }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- column -->
            </div>
{% endblock %}

{% block bread %}
<li class="breadcrumb-item active">Deshboard</li>
{% endblock %}

templates/Ace-file-add-realestate-add-property.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
{{ block.super }}
    <!-- page CSS -->
    <link href="{% static 'node_modules/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'node_modules/select2/dist/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'node_modules/switchery/dist/switchery.min.css' %}" rel="stylesheet" />
    <link href="{% static 'node_modules/bootstrap-select/bootstrap-select.min.css' %}" rel="stylesheet" />
    <link href="{% static 'node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css' %}" rel="stylesheet" />
    <link href="{% static 'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet" />
    <link href="{% static 'node_modules/multiselect/css/multi-select.css' %}" rel="stylesheet" type="text/css" />
{#this page css for sw#}
{#    <link href="{% static 'css/pages/bootstrap-switch.css' %}" rel="stylesheet">#}
{#    <link href="{% static 'node_modules/bootstrap-switch/bootstrap-switch.min.css' %}" rel="stylesheet">#}
{% endblock %}

{% block bread %}文件列表{% endblock %}
{% block content %}

  <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'sharefile:addfile' %}" class="pro-add-form" method="post" enctype="multipart/form-data">
                                    <div class="form-group">
                                        <label for="plocation">文件名称</label>
                                        <input name="filename" type="text" class="form-control" id="plocation" placeholder="文件名称"> </div>


{#                                       <div class="form-group">#}
{#                                            <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">#}
{#                                                Button with data-target#}
{#                                            </button>#}
{#                                            <div class="collapse" id="collapseExample">#}
{#                                                <div class="card card-body">#}
{#                                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.#}
{#                                                </div>#}
{#                                            </div>#}
{#                                       </div>#}










                                    <div class="form-group">
                                        <label for="pname">使用部门</label>
{#                                        <h5 class="m-t-20">Multiple select boxes</h5>#}
                                        <select name="dep" class="select2 m-b-10 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose">
                                            <optgroup label="请选择部门" name="deps">
                                                {% for user_dept in dept %}
                                                <option value="{{ user_dept.title }}" >{{ user_dept.title }}</option>
                                                {% endfor %}
                                            </optgroup>
                                        </select>

{#                                        <select name="filedepartment" class="form-control custom-select" id="city">#}
{#                                                 {% for deptfile in dept  %}#}
{#                                                <option >{{ deptfile.Department_name }}</option>#}
{#                                                {% endfor %}#}
{#                                        </select>#}

                                        <label for="pdesc">文件描述</label>
                                        <textarea name="filedes" class="form-control" rows="5" id="pdesc" placeholder="文件描述"></textarea>
                                    </div>






                                    <div class="form-group">
                                        <label class="control-label">发布方式</label>
                                            <select name="filetype" class="form-control custom-select" id="fb">

                                                <option>内部</option>
                                                <option>外部</option>

                                            </select>

                                    </div>


{#                                    <h5 class="card-title">Upload file</h5>#}

                                    <div class="form-group">
                                        <label class="control-label">文件用于</label>
                                            <select name="fileproject" class="form-control custom-select" id="city">
                                                {% for fileproject in project  %}
                                                <option>{{ fileproject.Project_name }}</option>
                                                {% endfor %}
                                            </select>

                                    </div>
                                    <div class="form-group">
                                        <label for="input-file-now">上传文件</label>
                                        <input name="fileupload" type="file" id="input-file-now" class="dropify" />
                                    </div>
                                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">添加文件</button>
                                    <button type="submit" class="btn btn-dark waves-effect waves-light">取消</button>
                                {% csrf_token %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock %}

{% block custom_js %}
    {{ block.super }}

    <script src="{% static 'myjs/myjs.js' %}"></script>

    <script src="{% static 'node_modules/inputmask/dist/min/jquery.inputmask.bundle.min.js' %}"></script>
    <script src="{% static 'js/pages/mask.init.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js' %}" type="text/javascript"></script>
{#    <!-- jQuery file upload -->#}
{#    <script src="{% static 'node_modules/dropify/dist/js/dropify.min.js' %}"></script>#}

    <!-- This page plugins -->
    <!-- ============================================================== -->
    <script src="{% static 'node_modules/switchery/dist/switchery.min.js' %}"></script>
    <script src="{% static 'node_modules/select2/dist/js/select2.full.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'node_modules/bootstrap-select/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'node_modules/multiselect/js/jquery.multi-select.js' %}"></script>


{#    for the mutiple choose#}
    <script>
    jQuery(document).ready(function() {
        // Switchery
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        $('.js-switch').each(function() {
            new Switchery($(this)[0], $(this).data());
        });
        // For select 2
        $(".select2").select2();
        $('.selectpicker').selectpicker();
        //Bootstrap-TouchSpin
        $(".vertical-spin").TouchSpin({
            verticalbuttons: true,
            verticalupclass: 'ti-plus',
            verticaldownclass: 'ti-minus'
        });
        var vspinTrue = $(".vertical-spin").TouchSpin({
            verticalbuttons: true
        });
        if (vspinTrue) {
            $('.vertical-spin').prev('.bootstrap-touchspin-prefix').remove();
        }
        $("input[name='tch1']").TouchSpin({
            min: 0,
            max: 100,
            step: 0.1,
            decimals: 2,
            boostat: 5,
            maxboostedstep: 10,
            postfix: '%'
        });
        $("input[name='tch2']").TouchSpin({
            min: -1000000000,
            max: 1000000000,
            stepinterval: 50,
            maxboostedstep: 10000000,
            prefix: '$'
        });
        $("input[name='tch3']").TouchSpin();
        $("input[name='tch3_22']").TouchSpin({
            initval: 40
        });
        $("input[name='tch5']").TouchSpin({
            prefix: "pre",
            postfix: "post"
        });
        // For multiselect
        $('#pre-selected-options').multiSelect();
        $('#optgroup').multiSelect({
            selectableOptgroup: true
        });
        $('#public-methods').multiSelect();
        $('#select-all').click(function() {
            $('#public-methods').multiSelect('select_all');
            return false;
        });
        $('#deselect-all').click(function() {
            $('#public-methods').multiSelect('deselect_all');
            return false;
        });
        $('#refresh').on('click', function() {
            $('#public-methods').multiSelect('refresh');
            return false;
        });
        $('#add-option').on('click', function() {
            $('#public-methods').multiSelect('addOption', {
                value: 42,
                text: 'test 42',
                index: 0
            });
            return false;
        });
        $(".ajax").select2({
            ajax: {
                url: "https://api.github.com/search/repositories",
                dataType: 'json',
                delay: 250,
                data: function(params) {
                    return {
                        q: params.term, // search term
                        page: params.page
                    };
                },
                processResults: function(data, params) {
                    // parse the results into the format expected by Select2
                    // since we are using custom formatting functions we do not need to
                    // alter the remote JSON data, except to indicate that infinite
                    // scrolling can be used
                    params.page = params.page || 1;
                    return {
                        results: data.items,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                cache: true
            },
            escapeMarkup: function(markup) {
                return markup;
            }, // let our custom formatter work
            minimumInputLength: 1,
            templateResult: formatRepo, // omitted for brevity, see the source of this page
            templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
        });
    });
    </script>



    
    
{% endblock %}

templates/indexAce.html
{% extends 'horizontal-base.html' %}